name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install uv and project dependencies
        run: |
          pip install --upgrade pip
          # Install uv from PyPI (uv is available on PyPI)
          pip install uv
          # Install project dependencies using uv lockfile
          uv sync

      - name: Run tests with coverage
        run: |
          uv run pytest --cov-branch --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: lere01/irorun
